version: "3"

services:
  frontend:
    container_name: frontend
    build:
      context: "./frontend"
    ports:
      - "3000:3000"

  hacking:
    container_name: hacking
    build:
      context: "./hacking"
    ports:
      - "4000:4000"

  database:
    image: 'mongo'
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test
    ports:
      - "7017:27017"
    volumes:
      - ./backend/files:/app/backend/files

  backend:
    depends_on:
      - database
    container_name: backend
    build:
      context: "./backend"
    ports:
      - "5000:5000"
    # Ensure that files folder is stored in the host machine, so data is not lost when the container is removed
    volumes:
      - ./backend/files:/app/backend/files
    environment: 
      - DB_HOST=database
      - DB_NAME=amazing-ctf
      - DB_PORT=27017
      - DB_ROOT_USERNAME=root
      - DB_PASSWORD=test
    
    

  # TODO: Decide the database and link it to the backend
