version: "3"

services:
  database:
    image: 'mongo'
    container_name: database
    # restart: always
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test
    ports:
      - "7017:27017"
    volumes:
      - ./database:/data/db

  backend:
    container_name: backend
    # restart: always
    build:
      context: "./backend"
    ports:
      - "5000:5000"
    # Ensure that files folder is stored in the host machine, so data is not lost when the container is removed
    volumes:
      - ./data:/app/data
    environment: 
      - DB_HOST=database
      - DB_NAME=amazing-ctf
      - DB_PORT=27017
      - DB_ROOT_USERNAME=root
      - DB_PASSWORD=test
    depends_on:
      - database

  frontend:
    container_name: frontend
    # restart: always
    build:
      context: "./frontend"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  hacking:
    container_name: hacking
    build:
      context: "./hacking"
    ports:
      - "4000:4000"
    depends_on:
      - backend
